/* Shows the total number of orders in our dataset */
SELECT COUNT(order_id) 
FROM orders;

/* Shows top 10 product category by number of items sold */
SELECT pct.product_category_name_english, COUNT(o.product_id)
FROM products p
JOIN order_items o
ON p.product_id = o.product_id
JOIN product_category_translations pct
ON p.product_category_name = pct.product_category_name
GROUP BY 1
ORDER BY 2 DESC
LIMIT 10;

/* Total revenue generated by each seller */
SELECT seller_id, SUM(price)
FROM order_items
GROUP BY 1
ORDER BY 2 DESC;

CREATE VIEW payment_per_order AS
SELECT order_id, SUM(payment_value) as order_total
FROM order_payments
GROUP BY 1;

/* Average order value */
SELECT AVG(order_total)
FROM payment_per_order;

/* Number of customers per state */
SELECT customer_state, COUNT(customer_id)
FROM customers
GROUP BY 1
ORDER BY 2 DESC;

/* Total orders and revenue per month */
SELECT EXTRACT(YEAR FROM o.order_approved_at) as year, EXTRACT(MONTH FROM o.order_approved_at) as month, COUNT( o.order_id) as total_orders, SUM(ppo.order_total) as total_revenue
FROM orders o
JOIN payment_per_order ppo
ON ppo.order_id = o.order_id
GROUP BY 1, 2;

/* Top 5 customers by spend */
SELECT o.customer_id, SUM(ppo.order_total)
FROM orders o
JOIN payment_per_order ppo
ON o.order_id = ppo.order_id
GROUP BY 1
ORDER BY 2 DESC
LIMIT 5;

/* Average review score per product category */
SELECT p.product_category_name, AVG(r.review_score)
FROM products p
JOIN order_items oi
ON p.product_id = oi.product_id
JOIN orders o
ON o.order_id = oi.order_id
JOIN order_reviews r
ON r.order_id = oi.order_id
GROUP BY 1
ORDER BY 2 DESC;

/* Orders with 4 or more items */
SELECT order_id, COUNT(order_item_id) AS number_of_items
FROM order_items
GROUP BY 1
HAVING COUNT(order_item_id) > 3
ORDER BY 2 DESC;

/* Orders delivered late */
SELECT order_id, order_delivered_customer_date - order_estimated_delivery_date as days_overdue
FROM orders
WHERE order_estimated_delivery_date < order_delivered_customer_date
ORDER BY 2 ASC;

/* Product category rank by total revenue */
SELECT p.product_category_name, SUM(oi.price) AS total_revenue,
  RANK() OVER (ORDER BY SUM(oi.price) DESC) AS revenue_rank
FROM order_items oi
JOIN products p ON p.product_id = oi.product_id
GROUP BY p.product_category_name
ORDER BY total_revenue DESC;

/* Running revenue total over time */
SELECT DATE(o.order_approved_at) AS day, SUM(ppo.order_total) AS daily_revenue,
  SUM(SUM(ppo.order_total)) OVER (ORDER BY DATE(o.order_approved_at)) AS cumulative_revenue
FROM orders o
JOIN payment_per_order ppo
ON o.order_id = ppo.order_id
GROUP BY 1
ORDER BY 1;

/* Running revenue total by Quarter */
WITH Quarter AS (
	SELECT EXTRACT(YEAR FROM o.order_approved_at) AS year, EXTRACT(QUARTER FROM o.order_approved_at) AS qtr, SUM(ppo.order_total) AS quarterly_revenue
FROM payment_per_order ppo
JOIN orders o
ON ppo.order_id = o.order_id
GROUP BY 1, 2)
SELECT year, qtr, quarterly_revenue,
	SUM(quarterly_revenue) OVER (ORDER BY year, qtr) AS cumulative_Revenue
FROM Quarter;

/* Difference in revenue per month */
WITH monthly AS (
  SELECT EXTRACT(YEAR  FROM o.order_approved_at) AS year, EXTRACT(MONTH FROM o.order_approved_at) AS month, SUM(ppo.order_total) AS monthly_income
FROM orders o
JOIN payment_per_order ppo
ON o.order_id = ppo.order_id
WHERE o.order_approved_at IS NOT NULL
GROUP BY 1, 2)
SELECT year, month, monthly_income,
  SUM(monthly_income) OVER (ORDER BY year, month) AS cumulative_revenue,
  monthly_income - LAG(monthly_income) OVER (ORDER BY year, month) AS revenue_difference
FROM monthly
ORDER BY year, month;

/* Current and previous order value by seller */
WITH seller_orders AS (
	SELECT oi.seller_id, oi.order_id, o.order_approved_at, SUM(oi.price) as order_value
FROM order_items oi
JOIN orders o
ON o.order_id = oi.order_id
GROUP BY 1,2,3)
SELECT seller_id, order_id, order_approved_at, order_value,
	LAG(order_value) OVER (PARTITION BY seller_id ORDER BY order_approved_at) as previous_order_value
FROM seller_orders;



